version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "adminmdp"
      POSTGRES_DB: "efrei"
    volumes:
    - sample-rest-api:/home/lokman/cours/master/sample-rest-api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
volumes:
  sample-rest-api:
